---
- name: Install Python with libs and copy project config
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Install packages
      ansible.builtin.apt:
        pkg:
        - python3
        - python3-pip
        - python3-psycopg2
        - python-django
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /opt/example.txt
        dest: /opt/example.txt
        owner: vagrant
        mode: '0644'